Repository lwarren01/fhir-works-on-aws-deployment, pull requests merged in 2022-04, with the labels that each got.

#32 CHP-212 enabled alarm and added subscription endpoint for audit, and archive cloudwatch alarms
  auditLogMover/serverless.yaml
  cloudformation/alarms.yaml
  scripts/install.sh
  serverless.yaml
Labels: size/s

#33 Added option for serverless.yml to source log level from environment …
  serverless.yaml
Labels: size/xs

#34 Feature/merge forks
  .gitignore
  .vscode/launch.json
  INSTALL.md
  archiveServiceLambda/index.ts
  auditLogMover/serverless.yaml
  cloudformation/alarms.yaml
  cloudformation/apiGateway.yaml
  cloudformation/archive.yaml
  cloudformation/bulkExport.yaml
  cloudformation/cloudwatchDashboard.yaml
  cloudformation/cognito.yaml
  cloudformation/synthetics.yaml
  package.json
  scripts/fhir-works-deploy-one-time-setup.sh
  scripts/fhir-works-local-develop.sh
  scripts/iam_policy.json
  scripts/install.sh
  serverless.yaml
  src/config.ts
  synthetics/README.md
  synthetics/metadata.js
  synthetics/uploadSyntheticsScriptsToS3.ts
  tsconfig.json
  yarn.lock
Labels: size/xl

#35 synthetics cron 5 minutes
  cloudformation/synthetics.yaml
Labels: size/s

#37 set roleManagedExternally to false for fresh install
  serverless.yaml
Labels: size/xs

#38 merge smart-develop to smart-mainline
  serverless.yaml
Labels: size/xs

#39 Set CloudWatch Log ARN externally created to API Gateway
  cloudformation/apiGateway.yaml
  serverless.yaml
Labels: size/xs

#40 Smart develop
  cloudformation/apiGateway.yaml
  serverless.yaml
Labels: size/xs
